/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej4;

import static ej4.Menu.listaProductos;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federico.acenjo
 */
public class BusquedaPorNombre extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form BusquedaPorNombre
     */
    public BusquedaPorNombre() {
        initComponents();
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLListadoNombre = new javax.swing.JLabel();
        jLEscribaChar = new javax.swing.JLabel();
        jTFCuadroBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBusquedaNombre = new javax.swing.JTable();

        setClosable(true);
        setTitle("BUSQUEDA POR NOMBRE");

        jLListadoNombre.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLListadoNombre.setText("LISTADO POR NOMBRE");

        jLEscribaChar.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLEscribaChar.setText("Escriba los primeros caracteres:");

        jTFCuadroBusqueda.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jTFCuadroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCuadroBusquedaKeyReleased(evt);
            }
        });

        jTBusquedaNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBusquedaNombre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEscribaChar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTFCuadroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLListadoNombre)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLListadoNombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEscribaChar)
                    .addComponent(jTFCuadroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCuadroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCuadroBusquedaKeyReleased
        borrarFilas();
        for (Producto producto : Menu.listaProductos) {
            if (producto.getDescripcion().toLowerCase().startsWith(jTFCuadroBusqueda.getText())){
                agregarProducto(producto);
            }
        } 
        if (jTFCuadroBusqueda.getText().isEmpty()){
            borrarFilas();
        }
    }//GEN-LAST:event_jTFCuadroBusquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEscribaChar;
    private javax.swing.JLabel jLListadoNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBusquedaNombre;
    private javax.swing.JTextField jTFCuadroBusqueda;
    // End of variables declaration//GEN-END:variables
    private void crearTabla(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jTBusquedaNombre.setModel(modelo);
    }
    
    private void agregarProducto(Producto producto){
        modelo.addRow(new Object []{
            producto.getCodigo(), 
            producto.getDescripcion(), 
            producto.getPrecio(), 
            producto.getStock()
        });
    }
    
    private void borrarFilas(){
        int f = modelo.getRowCount() - 1;
        
        for (;f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
