/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej4;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federico.acenjo
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form BusquedaPorPrecio
     */
    public BusquedaPorPrecio() {
        initComponents();
        crearTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFCuadroBusqueda2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBusquedaPrecio = new javax.swing.JTable();
        jLListadoPrecio = new javax.swing.JLabel();
        jLEscribaChar = new javax.swing.JLabel();
        jTFCuadroBusqueda1 = new javax.swing.JTextField();
        jLEscribaChar1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("BUSQUEDA POR PRECIO");

        jTFCuadroBusqueda2.setFont(new java.awt.Font("David", 1, 14)); // NOI18N

        jTBusquedaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBusquedaPrecio);

        jLListadoPrecio.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLListadoPrecio.setText("LISTADO POR PRECIO");

        jLEscribaChar.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLEscribaChar.setText("Entre $:");

        jTFCuadroBusqueda1.setFont(new java.awt.Font("David", 1, 14)); // NOI18N

        jLEscribaChar1.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLEscribaChar1.setText("Y");

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLListadoPrecio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEscribaChar)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCuadroBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLEscribaChar1)))
                .addGap(18, 18, 18)
                .addComponent(jTFCuadroBusqueda2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLListadoPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEscribaChar)
                    .addComponent(jTFCuadroBusqueda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCuadroBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEscribaChar1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double min = Double.parseDouble(jTFCuadroBusqueda1.getText());
        Double max = Double.parseDouble(jTFCuadroBusqueda2.getText());
        if (min > 0 && max > 0){
            busquedaPrecio(min, max);
        } else {
            JOptionPane.showMessageDialog(this, "No ha ingresado los datos necesarios");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLEscribaChar;
    private javax.swing.JLabel jLEscribaChar1;
    private javax.swing.JLabel jLListadoPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBusquedaPrecio;
    private javax.swing.JTextField jTFCuadroBusqueda1;
    private javax.swing.JTextField jTFCuadroBusqueda2;
    // End of variables declaration//GEN-END:variables
    private void crearTabla(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jTBusquedaPrecio.setModel(modelo);
    }
    
    private void agregarProducto(Producto producto){
        modelo.addRow(new Object []{
            producto.getCodigo(), 
            producto.getDescripcion(), 
            producto.getPrecio(), 
            producto.getStock()
        });
    }
    
    private void borrarFilas(){
        int f = modelo.getRowCount() - 1;
        
        for (;f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

    private void busquedaPrecio(Double min, Double max){
        borrarFilas();
        for (Producto producto : Menu.listaProductos) {
            if (producto.getPrecio() < max && producto.getPrecio() > min){
                agregarProducto(producto);
            }
        }
    }





}
