/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej4;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federico.acenjo
 */
public class BusquedaPorRubro extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    /**
     * Creates new form BusquedaPorRubro
     */
    public BusquedaPorRubro() {
        initComponents();
        crearTabla();
        crearItemComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBusquedaRubro = new javax.swing.JTable();
        jLListadoRubro = new javax.swing.JLabel();
        jLSeleccionRubro = new javax.swing.JLabel();
        jCBSeleccionRubro = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("BUSQUEDA POR RUBRO");

        jTBusquedaRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBusquedaRubro);

        jLListadoRubro.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLListadoRubro.setText("LISTADO POR NOMBRE");

        jLSeleccionRubro.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLSeleccionRubro.setText("Seleccione el rubro:");

        jCBSeleccionRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBSeleccionRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeleccionRubroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLSeleccionRubro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jCBSeleccionRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLListadoRubro)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLListadoRubro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionRubro)
                    .addComponent(jCBSeleccionRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBSeleccionRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeleccionRubroActionPerformed
        borrarFilas();
        filtrarRubro(jCBSeleccionRubro.getSelectedItem().toString());
    }//GEN-LAST:event_jCBSeleccionRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBSeleccionRubro;
    private javax.swing.JLabel jLListadoRubro;
    private javax.swing.JLabel jLSeleccionRubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBusquedaRubro;
    // End of variables declaration//GEN-END:variables
private void crearTabla(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jTBusquedaRubro.setModel(modelo);
    }
    
    private void agregarProducto(Producto producto){
        modelo.addRow(new Object []{
            producto.getCodigo(), 
            producto.getDescripcion(), 
            producto.getPrecio(), 
            producto.getStock()
        });
    }
    
    private void borrarFilas(){
        int f = modelo.getRowCount() - 1;
        for (;f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

    private void filtrarRubro(String rubro){
        for (Producto producto : Menu.listaProductos) {
            if (producto.getRubro().toString().equals(rubro)){
                agregarProducto(producto);
            }
        }
    }

    private void crearItemComboBox(){
        modeloComboBox.removeAllElements();
        jCBSeleccionRubro.setModel(modeloComboBox);
        for (Categoria categoria : Categoria.values()) {
            modeloComboBox.addElement(categoria);
        }
    }
    






}
