/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej4;

import java.util.TreeSet;

/**
 *
 * @author federico.acenjo
 */
public class Menu extends javax.swing.JFrame {

    public static TreeSet<Producto> listaProductos = new TreeSet<>();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarProductos(new Producto(15, "Tomate", 750.0, 100, Categoria.COMESTIBLE));
        cargarProductos(new Producto(17, "Palta", 500.0, 150, Categoria.COMESTIBLE));
        cargarProductos(new Producto(25, "Jabon", 550.0, 100, Categoria.LIMPIEZA));
        cargarProductos(new Producto(27, "Detergente", 650.0, 120, Categoria.LIMPIEZA));
        cargarProductos(new Producto(35, "Talco", 850.0, 100, Categoria.PERFUMERIA));
        cargarProductos(new Producto(37, "Desodorante", 450.0, 80, Categoria.PERFUMERIA));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAdministracion = new javax.swing.JMenu();
        jMAdmIProductos = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMConIRubro = new javax.swing.JMenuItem();
        jMConINombre = new javax.swing.JMenuItem();
        jMConIPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jMAdministracion.setText("Administracion");

        jMAdmIProductos.setText("Productos");
        jMAdmIProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAdmIProductosActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMAdmIProductos);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        jMConIRubro.setText("Por Rubro");
        jMConIRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConIRubroActionPerformed(evt);
            }
        });
        jMConsultas.add(jMConIRubro);

        jMConINombre.setText("Por Nombre");
        jMConINombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConINombreActionPerformed(evt);
            }
        });
        jMConsultas.add(jMConINombre);

        jMConIPrecio.setText("Por Precio");
        jMConIPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConIPrecioActionPerformed(evt);
            }
        });
        jMConsultas.add(jMConIPrecio);

        jMenuBar1.add(jMConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMConIRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConIRubroActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();

        BusquedaPorRubro bpr = new BusquedaPorRubro();
        bpr.setVisible(true);
        jDEscritorio.add(bpr);
        jDEscritorio.moveToFront(bpr);
    }//GEN-LAST:event_jMConIRubroActionPerformed

    private void jMConINombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConINombreActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();

        BusquedaPorNombre bpn = new BusquedaPorNombre();
        bpn.setVisible(true);
        jDEscritorio.add(bpn);
        jDEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMConINombreActionPerformed

    private void jMConIPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConIPrecioActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();

        BusquedaPorPrecio bpp = new BusquedaPorPrecio();
        bpp.setVisible(true);
        jDEscritorio.add(bpp);
        jDEscritorio.moveToFront(bpp);
    }//GEN-LAST:event_jMConIPrecioActionPerformed

    private void jMAdmIProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAdmIProductosActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();

        GestionProductos gp = new GestionProductos();
        gp.setVisible(true);
        jDEscritorio.add(gp);
        jDEscritorio.moveToFront(gp);
    }//GEN-LAST:event_jMAdmIProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenuItem jMAdmIProductos;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenuItem jMConINombre;
    private javax.swing.JMenuItem jMConIPrecio;
    private javax.swing.JMenuItem jMConIRubro;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    private void cargarProductos(Producto producto) {
        listaProductos.add(producto);
    }

}
